- name: frontend configuration
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: nginx service
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes  

  - name: Remove file (delete file)
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent   

  - name: create a index   
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: directory 

  - name: download the code
    ansible.builtin.get-url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend

  - name: exact the code
    ansible_built.file
    src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html 
    remote_src: yes
    


