- name: install mysql
  hosts: mysql
  become: yes
  vars: 
   mysql_root_password: ExpenseApp@1
   login_host: mysql.learningdevops.shop
  tasks: 
  - name: ansible to install PyMysql
    ansible.builtin.pip3:
     - name: PyMysql
    executable: pip3.9
    
  - name: install mysql
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: start the service
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes  

  - name: connect to mysql server
    community.mysql.mysql_info:
     login_user: root
     login_password: " {{ mysql_root_password }} "   
     login_host: " {{ login_host}} "
     ignore_errors: true
     register: mysql_info

  - name: print mysql info
    ansible.builtin.debug:
     msg: "{{ mysql_info }}"
