- name: install mysql
  hosts: mysql
  because: yes
  tasks: 
  - name: install mysql
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: start the service
    ansible.builtin.service:
     name: mysqld
     state: restarted
     enabled: yes  